# Generated by Django 5.2.11 on 2026-03-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paperpage",
            name="is_title",
            field=models.BooleanField(default=False),
        ),
    ]
